[package]
name = "cotton_userspace"
version = "0.1.0"
edition = "2021"
authors = ["aryansrao"]
description = "CottonOS userspace programs"

[lib]
name = "cotton_userspace"
path = "src/lib.rs"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
